apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: myidentity
spec:
  type: 0
  ResourceID: /subscriptions/adc3e911-cfc5-4ff2-a175-0c462e4da824/resourcegroups/AKSCluster/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myidentity
  ClientID: 69f5f5cb-fb7c-4aae-80b4-6ed7da647f51